In [ ]:
import json
import pandas as pd
import os

In [ ]:


print(os.getcwd())
print(os.listdir())

/content
['.config', 'sample_data']

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving data.tar.bz2 to data.tar.bz2

In [ ]:
import tarfile

with tarfile.open("data.tar.bz2", "r:bz2") as tar:
    tar.extractall()

/tmp/ipykernel_4306/406351965.py:4: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall()

In [ ]:
import os

print(os.listdir("data"))

['test.jsonl', 'test.db', 'train.jsonl', 'dev.db', 'train.tables.jsonl', 'dev.jsonl', 'dev.tables.jsonl', 'train.db', 'test.tables.jsonl']

In [ ]:


with open("data/train.jsonl", "r", encoding="utf-8") as f:
    train_data = [json.loads(line) for line in f]

In [ ]:
len(train_data)

56355

In [ ]:
# first table
train_data[0]

{'phase': 1,
 'table_id': '1-1000181-1',
 'question': 'Tell me what the notes are for South Australia ',
 'sql': {'sel': 5, 'conds': [[3, 0, 'SOUTH AUSTRALIA']], 'agg': 0}}

In [ ]:
with open("data/train.tables.jsonl", "r", encoding="utf-8") as f:
    train_tables = [json.loads(line) for line in f]

In [ ]:
len(train_tables)

18585

In [ ]:
train_tables[0]

{'id': '1-1000181-1',
 'header': ['State/territory',
  'Text/background colour',
  'Format',
  'Current slogan',
  'Current series',
  'Notes'],
 'types': ['text', 'text', 'text', 'text', 'text', 'text'],
 'rows': [['Australian Capital Territory',
   'blue/white',
   'Yaa·nna',
   'ACT · CELEBRATION OF A CENTURY 2013',
   'YIL·00A',
   'Slogan screenprinted on plate'],
  ['New South Wales',
   'black/yellow',
   'aa·nn·aa',
   'NEW SOUTH WALES',
   'BX·99·HI',
   'No slogan on current series'],
  ['New South Wales',
   'black/white',
   'aaa·nna',
   'NSW',
   'CPX·12A',
   'Optional white slimline series'],
  ['Northern Territory',
   'ochre/white',
   'Ca·nn·aa',
   'NT · OUTBACK AUSTRALIA',
   'CB·06·ZZ',
   'New series began in June 2011'],
  ['Queensland',
   'maroon/white',
   'nnn·aaa',
   'QUEENSLAND · SUNSHINE STATE',
   '999·TLG',
   'Slogan embossed on plate'],
  ['South Australia',
   'black/white',
   'Snnn·aaa',
   'SOUTH AUSTRALIA',
   'S000·AZD',
   'No slogan on current series'],
  ['Victoria',
   'blue/white',
   'aaa·nnn',
   'VICTORIA - THE PLACE TO BE',
   'ZZZ·562',
   'Current series will be exhausted this year']],
 'name': 'table_1000181_1'}

In [ ]:
sample = train_data[1]

print("Question:")
print(sample["question"])

print("\nSQL:")
print(sample["sql"])

print("\nTable ID:")
print(sample["table_id"])

Question:
What is the current series where the new series began in June 2011?

SQL:
{'sel': 4, 'conds': [[5, 0, 'New series began in June 2011']], 'agg': 0}

Table ID:
1-1000181-1

In [ ]:
table = next(
    t for t in train_tables
    if t["id"] == sample["table_id"]
)

In [ ]:
df = pd.DataFrame(table["rows"], columns=table["header"])

display(df)

,State/territory,Text/background colour,Format,Current slogan,Current series,Notes
0,Australian Capital Territory,blue/white,Yaa·nna,ACT · CELEBRATION OF A CENTURY 2013,YIL·00A,Slogan screenprinted on plate
1,New South Wales,black/yellow,aa·nn·aa,NEW SOUTH WALES,BX·99·HI,No slogan on current series
2,New South Wales,black/white,aaa·nna,NSW,CPX·12A,Optional white slimline series
3,Northern Territory,ochre/white,Ca·nn·aa,NT · OUTBACK AUSTRALIA,CB·06·ZZ,New series began in June 2011
4,Queensland,maroon/white,nnn·aaa,QUEENSLAND · SUNSHINE STATE,999·TLG,Slogan embossed on plate
5,South Australia,black/white,Snnn·aaa,SOUTH AUSTRALIA,S000·AZD,No slogan on current series
6,Victoria,blue/white,aaa·nnn,VICTORIA - THE PLACE TO BE,ZZZ·562,Current series will be exhausted this year

---------------------------------------------------------------

In [ ]:


with open("data/train.tables.jsonl", "r", encoding="utf-8") as f:
    train_tables = [json.loads(line) for line in f]

In [ ]:
#number of tables
len(train_tables)

18585

In [ ]:
#first table
train_tables[0]

{'id': '1-1000181-1',
 'header': ['State/territory',
  'Text/background colour',
  'Format',
  'Current slogan',
  'Current series',
  'Notes'],
 'types': ['text', 'text', 'text', 'text', 'text', 'text'],
 'rows': [['Australian Capital Territory',
   'blue/white',
   'Yaa·nna',
   'ACT · CELEBRATION OF A CENTURY 2013',
   'YIL·00A',
   'Slogan screenprinted on plate'],
  ['New South Wales',
   'black/yellow',
   'aa·nn·aa',
   'NEW SOUTH WALES',
   'BX·99·HI',
   'No slogan on current series'],
  ['New South Wales',
   'black/white',
   'aaa·nna',
   'NSW',
   'CPX·12A',
   'Optional white slimline series'],
  ['Northern Territory',
   'ochre/white',
   'Ca·nn·aa',
   'NT · OUTBACK AUSTRALIA',
   'CB·06·ZZ',
   'New series began in June 2011'],
  ['Queensland',
   'maroon/white',
   'nnn·aaa',
   'QUEENSLAND · SUNSHINE STATE',
   '999·TLG',
   'Slogan embossed on plate'],
  ['South Australia',
   'black/white',
   'Snnn·aaa',
   'SOUTH AUSTRALIA',
   'S000·AZD',
   'No slogan on current series'],
  ['Victoria',
   'blue/white',
   'aaa·nnn',
   'VICTORIA - THE PLACE TO BE',
   'ZZZ·562',
   'Current series will be exhausted this year']],
 'name': 'table_1000181_1'}

In [ ]:
#first table header
train_tables[0]["header"]

['State/territory',
 'Text/background colour',
 'Format',
 'Current slogan',
 'Current series',
 'Notes']

In [ ]:
train_tables[1]["header"]

['Aircraft',
 'Description',
 'Max Gross Weight',
 'Total disk area',
 'Max disk Loading']

In [ ]:
#all rows of table 0
train_tables[0]["rows"][0]

['Australian Capital Territory',
 'blue/white',
 'Yaa·nna',
 'ACT · CELEBRATION OF A CENTURY 2013',
 'YIL·00A',
 'Slogan screenprinted on plate']

In [ ]:
#converting train_tables[0] to dataframe

table0 = pd.DataFrame(
    train_tables[0]["rows"],
    columns=train_tables[0]["header"]
)

display(table0)

,State/territory,Text/background colour,Format,Current slogan,Current series,Notes
0,Australian Capital Territory,blue/white,Yaa·nna,ACT · CELEBRATION OF A CENTURY 2013,YIL·00A,Slogan screenprinted on plate
1,New South Wales,black/yellow,aa·nn·aa,NEW SOUTH WALES,BX·99·HI,No slogan on current series
2,New South Wales,black/white,aaa·nna,NSW,CPX·12A,Optional white slimline series
3,Northern Territory,ochre/white,Ca·nn·aa,NT · OUTBACK AUSTRALIA,CB·06·ZZ,New series began in June 2011
4,Queensland,maroon/white,nnn·aaa,QUEENSLAND · SUNSHINE STATE,999·TLG,Slogan embossed on plate
5,South Australia,black/white,Snnn·aaa,SOUTH AUSTRALIA,S000·AZD,No slogan on current series
6,Victoria,blue/white,aaa·nnn,VICTORIA - THE PLACE TO BE,ZZZ·562,Current series will be exhausted this year

In [ ]:
table0.shape

(7, 6)

In [ ]:
# a particular table by chnaging t["id"]
table = next(
    t for t in train_tables
    if t["id"] == "1-1000181-1"
)

In [ ]:
example = train_data[0]

print(example)

{'phase': 1, 'table_id': '1-1000181-1', 'question': 'Tell me what the notes are for South Australia ', 'sql': {'sel': 5, 'conds': [[3, 0, 'SOUTH AUSTRALIA']], 'agg': 0}}

In [ ]:
print("Question:", example["question"])
print("Table ID:", example["table_id"])
print("SQL:", example["sql"])

Question: Tell me what the notes are for South Australia
Table ID: 1-1000181-1
SQL: {'sel': 5, 'conds': [[3, 0, 'SOUTH AUSTRALIA']], 'agg': 0}

In [ ]:
table = next(
    t for t in train_tables
    if t["id"] == example["table_id"]
)

In [ ]:
print(table["header"])

['State/territory', 'Text/background colour', 'Format', 'Current slogan', 'Current series', 'Notes']

In [ ]:
display(pd.DataFrame(
    table["rows"],
    columns=table["header"]
))

,State/territory,Text/background colour,Format,Current slogan,Current series,Notes
0,Australian Capital Territory,blue/white,Yaa·nna,ACT · CELEBRATION OF A CENTURY 2013,YIL·00A,Slogan screenprinted on plate
1,New South Wales,black/yellow,aa·nn·aa,NEW SOUTH WALES,BX·99·HI,No slogan on current series
2,New South Wales,black/white,aaa·nna,NSW,CPX·12A,Optional white slimline series
3,Northern Territory,ochre/white,Ca·nn·aa,NT · OUTBACK AUSTRALIA,CB·06·ZZ,New series began in June 2011
4,Queensland,maroon/white,nnn·aaa,QUEENSLAND · SUNSHINE STATE,999·TLG,Slogan embossed on plate
5,South Australia,black/white,Snnn·aaa,SOUTH AUSTRALIA,S000·AZD,No slogan on current series
6,Victoria,blue/white,aaa·nnn,VICTORIA - THE PLACE TO BE,ZZZ·562,Current series will be exhausted this year

In [ ]:
table0.duplicated().sum()

np.int64(0)

In [ ]:
table0.head(1)

,State/territory,Text/background colour,Format,Current slogan,Current series,Notes
0,Australian Capital Territory,blue/white,Yaa·nna,ACT · CELEBRATION OF A CENTURY 2013,YIL·00A,Slogan screenprinted on plate

--------------------------------------------------------

In [ ]:
import json
import pandas as pd

with open("data/train.jsonl", "r", encoding="utf-8") as f:
    train_data = [json.loads(line) for line in f]

with open("data/train.tables.jsonl", "r", encoding="utf-8") as f:
    train_tables = [json.loads(line) for line in f]

In [ ]:
table_dict = {table["id"]: table for table in train_tables}

In [ ]:
table_dict["1-1000181-1"]

{'id': '1-1000181-1',
 'header': ['State/territory',
  'Text/background colour',
  'Format',
  'Current slogan',
  'Current series',
  'Notes'],
 'types': ['text', 'text', 'text', 'text', 'text', 'text'],
 'rows': [['Australian Capital Territory',
   'blue/white',
   'Yaa·nna',
   'ACT · CELEBRATION OF A CENTURY 2013',
   'YIL·00A',
   'Slogan screenprinted on plate'],
  ['New South Wales',
   'black/yellow',
   'aa·nn·aa',
   'NEW SOUTH WALES',
   'BX·99·HI',
   'No slogan on current series'],
  ['New South Wales',
   'black/white',
   'aaa·nna',
   'NSW',
   'CPX·12A',
   'Optional white slimline series'],
  ['Northern Territory',
   'ochre/white',
   'Ca·nn·aa',
   'NT · OUTBACK AUSTRALIA',
   'CB·06·ZZ',
   'New series began in June 2011'],
  ['Queensland',
   'maroon/white',
   'nnn·aaa',
   'QUEENSLAND · SUNSHINE STATE',
   '999·TLG',
   'Slogan embossed on plate'],
  ['South Australia',
   'black/white',
   'Snnn·aaa',
   'SOUTH AUSTRALIA',
   'S000·AZD',
   'No slogan on current series'],
  ['Victoria',
   'blue/white',
   'aaa·nnn',
   'VICTORIA - THE PLACE TO BE',
   'ZZZ·562',
   'Current series will be exhausted this year']],
 'name': 'table_1000181_1'}

In [ ]:
data = []

for item in train_data:
    table = table_dict[item["table_id"]]

    schema = " | ".join(table["header"])

    sql = json.dumps(item["sql"])

    data.append({
        "question": item["question"],
        "schema": schema,
        "sql": sql
    })

df = pd.DataFrame(data)

df.head()

,question,schema,sql
0,Tell me what the notes are for South Australia,State/territory | Text/background colour | For...,"{""sel"": 5, ""conds"": [[3, 0, ""SOUTH AUSTRALIA""]..."
1,What is the current series where the new serie...,State/territory | Text/background colour | For...,"{""sel"": 4, ""conds"": [[5, 0, ""New series began ..."
2,What is the format for South Australia?,State/territory | Text/background colour | For...,"{""sel"": 2, ""conds"": [[0, 0, ""South Australia""]..."
3,Name the background colour for the Australian ...,State/territory | Text/background colour | For...,"{""sel"": 1, ""conds"": [[0, 0, ""Australian Capita..."
4,how many times is the fuel propulsion is cng?,Order Year | Manufacturer | Model | Fleet Seri...,"{""sel"": 3, ""conds"": [[5, 0, ""CNG""]], ""agg"": 3}"

In [ ]:
df["input_text"] = (
    "Question: " + df["question"] +
    " Table: " + df["schema"]
)

In [ ]:
df[["input_text", "sql"]].head()

,input_text,sql
0,Question: Tell me what the notes are for South...,"{""sel"": 5, ""conds"": [[3, 0, ""SOUTH AUSTRALIA""]..."
1,Question: What is the current series where the...,"{""sel"": 4, ""conds"": [[5, 0, ""New series began ..."
2,Question: What is the format for South Austral...,"{""sel"": 2, ""conds"": [[0, 0, ""South Australia""]..."
3,Question: Name the background colour for the A...,"{""sel"": 1, ""conds"": [[0, 0, ""Australian Capita..."
4,Question: how many times is the fuel propulsio...,"{""sel"": 3, ""conds"": [[5, 0, ""CNG""]], ""agg"": 3}"

In [ ]:
import re

def remove_html(text):
    text = re.sub(r"<[^>]+>", " ", text)
    return text

In [ ]:
df["input_text"] = df["input_text"].apply(remove_html)

In [ ]:
def clean_text(text):
    text = re.sub(r"\s+", " ", text)
    return text.strip()

In [ ]:
df["input_text"] = df["input_text"].apply(clean_text)

In [ ]:
df[["input_text", "sql"]].head()

,input_text,sql
0,Question: Tell me what the notes are for South...,"{""sel"": 5, ""conds"": [[3, 0, ""SOUTH AUSTRALIA""]..."
1,Question: What is the current series where the...,"{""sel"": 4, ""conds"": [[5, 0, ""New series began ..."
2,Question: What is the format for South Austral...,"{""sel"": 2, ""conds"": [[0, 0, ""South Australia""]..."
3,Question: Name the background colour for the A...,"{""sel"": 1, ""conds"": [[0, 0, ""Australian Capita..."
4,Question: how many times is the fuel propulsio...,"{""sel"": 3, ""conds"": [[5, 0, ""CNG""]], ""agg"": 3}"

In [ ]:
df.shape

(56355, 4)

In [ ]:
print(df.isnull().sum())

question      0
schema        0
sql           0
input_text    0
dtype: int64

In [ ]:
!pip install transformers sentencepiece

Requirement already satisfied: transformers in /usr/local/lib/python3.13/dist-packages (5.18.0)
Requirement already satisfied: sentencepiece in /usr/local/lib/python3.13/dist-packages (0.2.2)
Requirement already satisfied: huggingface-hub<3.0,>=1.31.0 in /usr/local/lib/python3.13/dist-packages (from transformers) (1.33.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.13/dist-packages (from transformers) (2.1.3)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.13/dist-packages (from transformers) (26.3)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.13/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.13/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<0.24.0,>=0.23.1 in /usr/local/lib/python3.13/dist-packages (from transformers) (0.23.2)
Requirement already satisfied: typer in /usr/local/lib/python3.13/dist-packages (from transformers) (0.27.2)
Requirement already satisfied: safetensors>=0.8.0 in /usr/local/lib/python3.13/dist-packages (from transformers) (0.8.0)
Requirement already satisfied: tqdm>=4.60 in /usr/local/lib/python3.13/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<3.0,>=1.31.0->transformers) (8.5.0)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<3.0,>=1.31.0->transformers) (4.0.7)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<3.0,>=1.31.0->transformers) (2025.12.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.6.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<3.0,>=1.31.0->transformers) (1.6.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<3.0,>=1.31.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<3.0,>=1.31.0->transformers) (4.16.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.13/dist-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.13/dist-packages (from typer->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.13/dist-packages (from typer->transformers) (0.0.5)
Requirement already satisfied: anyio in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<3.0,>=1.31.0->transformers) (4.15.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<3.0,>=1.31.0->transformers) (2026.7.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<3.0,>=1.31.0->transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<3.0,>=1.31.0->transformers) (3.20)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.13/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<3.0,>=1.31.0->transformers) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.13/dist-packages (from rich>=13.8.0->typer->transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.13/dist-packages (from rich>=13.8.0->typer->transformers) (2.21.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.13/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers) (0.1.2)

In [ ]:
from transformers import AutoTokenizer

In [ ]:
tokenizer = AutoTokenizer.from_pretrained("t5-small")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/1.21k [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/2.32k [00:00<?, ?B/s]

spiece.model:   0%|          | 0.00/792k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.39M [00:00<?, ?B/s]

In [ ]:
inputs = tokenizer(
    df["input_text"].tolist(),
    padding=True,
    truncation=True,
    max_length=256
)

In [ ]:
df["sql"]

0        {"sel": 5, "conds": [[3, 0, "SOUTH AUSTRALIA"]...
1        {"sel": 4, "conds": [[5, 0, "New series began ...
2        {"sel": 2, "conds": [[0, 0, "South Australia"]...
3        {"sel": 1, "conds": [[0, 0, "Australian Capita...
4           {"sel": 3, "conds": [[5, 0, "CNG"]], "agg": 3}
                               ...
56350       {"sel": 1, "conds": [[5, 0, "3-2"]], "agg": 0}
56351    {"sel": 4, "conds": [[3, 0, "aston villa"]], "...
56352    {"sel": 2, "conds": [[4, 0, "san siro"], [1, 0...
56353    {"sel": 5, "conds": [[0, 0, "redwood school"]]...
56354    {"sel": 5, "conds": [[1, 0, "tripoli"]], "agg"...
Name: sql, Length: 56355, dtype: object

In [ ]:
targets = tokenizer(
    df["sql"].tolist(),
    padding=True,
    truncation=True,
    max_length=128
)

In [ ]:
print("Original input:")
print(df["input_text"].iloc[0])

print("\nToken IDs:")
print(inputs["input_ids"][0])

print("\nOriginal output:")
print(df["sql"].iloc[0])

print("\nTarget token IDs:")
print(targets["input_ids"][0])

Original input:
Question: Tell me what the notes are for South Australia Table: State/territory | Text/background colour | Format | Current slogan | Current series | Notes

Token IDs:
[11860, 10, 8779, 140, 125, 8, 3358, 33, 21, 1013, 2051, 4398, 10, 1015, 87, 17, 21301, 10972, 1820, 5027, 87, 1549, 9232, 3243, 1820, 12439, 1820, 12892, 22031, 1820, 12892, 939, 1820, 2507, 7, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

Original output:
{"sel": 5, "conds": [[3, 0, "SOUTH AUSTRALIA"]], "agg": 0}

Target token IDs:
[3, 2, 121, 7, 15, 40, 121, 10, 7836, 96, 1018, 26, 7, 121, 10, 784, 6306, 6355, 8014, 96, 134, 9744, 566, 3, 6727, 13733, 24933, 188, 121, 908, 13679, 96, 9, 4102, 121, 10, 3, 632, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [ ]:
df["target"] = df["sql"].apply(lambda x: json.loads(x)["sel"])

print(df[["input_text", "target"]].head())

                                          input_text  target
0  Question: Tell me what the notes are for South...       5
1  Question: What is the current series where the...       4
2  Question: What is the format for South Austral...       2
3  Question: Name the background colour for the A...       1
4  Question: how many times is the fuel propulsio...       3

In [ ]:
from sklearn.model_selection import train_test_split

X = df["input_text"]
y = df["target"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(
    max_features=5000
)

X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

In [ ]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

model.fit(X_train_vec, y_train)

RandomForestClassifier(random_state=42)

In [ ]:
y_pred = model.predict(X_test_vec)

In [ ]:
question = "What are the notes for South Australia?"
schema = " | ".join(train_tables[0]["header"])

input_text = "Question: " + question + " Table: " + schema

print(input_text)
input_vec = vectorizer.transform([input_text])
prediction = model.predict(input_vec)

print("Predicted output:", prediction[0])

Question: What are the notes for South Australia? Table: State/territory | Text/background colour | Format | Current slogan | Current series | Notes
Predicted output: 2

In [ ]:
!pip install -q transformers sentencepiece datasets accelerate

In [ ]:
def make_sql(item, table):
    sql_data = item["sql"]

    select_col = table["header"][sql_data["sel"]]

    sql = "SELECT " + select_col

    if sql_data["agg"] != 0:
        agg = ["", "MAX", "MIN", "COUNT", "SUM", "AVG"][sql_data["agg"]]
        sql = "SELECT " + agg + "(" + select_col + ")"

    if len(sql_data["conds"]) > 0:
        conditions = []

        for cond in sql_data["conds"]:
            col = table["header"][cond[0]]
            op = ["=", ">", "<"][cond[1]]
            value = cond[2]

            conditions.append(
                col + " " + op + " '" + value + "'"
            )

        sql += " WHERE " + " AND ".join(conditions)

    return sql

In [ ]:
item = train_data[0]
table = table_dict[item["table_id"]]

print(make_sql(item, table))

SELECT Notes WHERE Current slogan = 'SOUTH AUSTRALIA'

In [ ]:
def make_sql(item, table):
    sql_data = item["sql"]

    select_col = table["header"][sql_data["sel"]]

    sql = "SELECT " + select_col

    if sql_data["agg"] != 0:
        agg = ["", "MAX", "MIN", "COUNT", "SUM", "AVG"][sql_data["agg"]]
        sql = "SELECT " + agg + "(" + select_col + ")"

    if len(sql_data["conds"]) > 0:
        conditions = []

        for cond in sql_data["conds"]:
            col = table["header"][cond[0]]
            op = ["=", ">", "<"][cond[1]]
            value = cond[2]

            conditions.append(
                col + " " + op + " '" + str(value) + "'"
            )

        sql += " WHERE " + " AND ".join(conditions)

    return sql

In [ ]:
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

tokenizer = AutoTokenizer.from_pretrained("t5-small")

model = AutoModelForSeq2SeqLM.from_pretrained("t5-small")

model.safetensors: reconstructing file:   0%|          |  0.00B /  242MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/131 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/147 [00:00<?, ?B/s]

In [ ]:
inputs = tokenizer(
    df["input_text"].tolist(),
    max_length=256,
    padding="max_length",
    truncation=True
)

labels = tokenizer(
    df["sql"].tolist(),
    max_length=128,
    padding="max_length",
    truncation=True
)

In [ ]:
from datasets import Dataset

dataset = Dataset.from_pandas(
    pd.DataFrame({
        "input_ids": inputs["input_ids"],
        "attention_mask": inputs["attention_mask"],
        "labels": labels["input_ids"]
    })
)

In [ ]:
def fix_labels(example):
    example["labels"] = [
        -100 if token == tokenizer.pad_token_id else token
        for token in example["labels"]
    ]
    return example

dataset = dataset.map(fix_labels)

Map:   0%|          | 0/56355 [00:00<?, ? examples/s]

In [ ]:
print(dataset)

Dataset({
    features: ['input_ids', 'attention_mask', 'labels'],
    num_rows: 56355
})

In [ ]:
print(dataset[0])

{'input_ids': [11860, 10, 8779, 140, 125, 8, 3358, 33, 21, 1013, 2051, 4398, 10, 1015, 87, 17, 21301, 10972, 1820, 5027, 87, 1549, 9232, 3243, 1820, 12439, 1820, 12892, 22031, 1820, 12892, 939, 1820, 2507, 7, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'labels': [3, 2, 121, 7, 15, 40, 121, 10, 7836, 96, 1018, 26, 7, 121, 10, 784, 6306, 6355, 8014, 96, 134, 9744, 566, 3, 6727, 13733, 24933, 188, 121, 908, 13679, 96, 9, 4102, 121, 10, 3, 632, 2, 1, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100]}

In [ ]:
dataset_split = dataset.train_test_split(
    test_size=0.1,
    seed=42
)

train_dataset = dataset_split["train"]
val_dataset = dataset_split["test"]

In [ ]:
print("Training:", len(train_dataset))
print("Validation:", len(val_dataset))

Training: 50719
Validation: 5636

In [ ]:
from transformers import AutoModelForSeq2SeqLM

model = AutoModelForSeq2SeqLM.from_pretrained("t5-small")

Loading weights:   0%|          | 0/131 [00:00<?, ?it/s]

In [ ]:
from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir="./t5_wikisql",
    num_train_epochs=3,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    eval_strategy="epoch",
    save_strategy="epoch",
    logging_steps=100,
    report_to="none"
)

In [ ]:
from transformers import Trainer

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset
)

In [ ]:
trainer.train()

/usr/local/lib/python3.13/dist-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

In [ ]:
question = "What are the notes for South Australia?"

schema = " | ".join(train_tables[0]["header"])

input_text = (
    "translate English to SQL: "
    + "Question: " + question
    + " Schema: " + schema
)

inputs = tokenizer(
    input_text,
    return_tensors="pt",
    max_length=256,
    truncation=True
)

inputs = {key: value.to(model.device) for key, value in inputs.items()}

outputs = model.generate(
    **inputs,
    max_length=128
)

prediction = tokenizer.decode(
    outputs[0],
    skip_special_tokens=True
)

print("Question:", question)
print("Generated SQL:", prediction)

In [ ]:
import json
import pandas as pd

with open("data/test.jsonl", "r", encoding="utf-8") as f:
    test_data = [json.loads(line) for line in f]

with open("data/test.tables.jsonl", "r", encoding="utf-8") as f:
    test_tables = [json.loads(line) for line in f]

test_table_dict = {table["id"]: table for table in test_tables}

print("Test examples:", len(test_data))
print("Test tables:", len(test_tables))

In [ ]:
test_rows = []

for item in test_data:
    table = test_table_dict[item["table_id"]]

    schema = " | ".join(table["header"])

    sql = make_sql(item, table)

    test_rows.append({
        "question": item["question"],
        "schema": schema,
        "sql": sql
    })

test_df = pd.DataFrame(test_rows)

In [ ]:
test_df["input_text"] = (
    "translate English to SQL: "
    + "Question: " + test_df["question"]
    + " Schema: " + test_df["schema"]
)

In [ ]:
predictions = []

model.eval()

for text in test_df["input_text"]:
    inputs = tokenizer(
        text,
        return_tensors="pt",
        max_length=256,
        truncation=True
    )

    inputs = {
        key: value.to(model.device)
        for key, value in inputs.items()
    }

    outputs = model.generate(
        **inputs,
        max_length=128
    )

    prediction = tokenizer.decode(
        outputs[0],
        skip_special_tokens=True
    )

    predictions.append(prediction)

test_df["predicted_sql"] = predictions

In [ ]:
for i in range(10):
    print("QUESTION:")
    print(test_df.iloc[i]["question"])

    print("\nACTUAL SQL:")
    print(test_df.iloc[i]["sql"])

    print("\nPREDICTED SQL:")
    print(test_df.iloc[i]["predicted_sql"])

    print("=" * 80)

In [ ]:
def normalize_sql(sql):
    return " ".join(sql.lower().strip().split())

In [ ]:
actual = test_df["sql"].apply(normalize_sql)
predicted = test_df["predicted_sql"].apply(normalize_sql)

exact_match_accuracy = (actual == predicted).mean()

print("Exact Match Accuracy:", exact_match_accuracy)

In [ ]:
from sklearn.metrics import precision_score, recall_score, f1_score

In [ ]:
y_true = []
y_pred = []

for actual_sql, predicted_sql in zip(
    test_df["sql"],
    test_df["predicted_sql"]
):
    actual_tokens = normalize_sql(actual_sql).split()
    predicted_tokens = normalize_sql(predicted_sql).split()

    max_len = max(len(actual_tokens), len(predicted_tokens))

    actual_tokens += ["<PAD>"] * (max_len - len(actual_tokens))
    predicted_tokens += ["<PAD>"] * (max_len - len(predicted_tokens))

    y_true.extend(actual_tokens)
    y_pred.extend(predicted_tokens)

In [ ]:
precision = precision_score(
    y_true,
    y_pred,
    average="weighted",
    zero_division=0
)

recall = recall_score(
    y_true,
    y_pred,
    average="weighted",
    zero_division=0
)

f1 = f1_score(
    y_true,
    y_pred,
    average="weighted",
    zero_division=0
)

print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

In [ ]:
print("Test Results")
print("-" * 40)
print("Exact Match Accuracy:", exact_match_accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)